#!/usr/bin/env python3
"""在有界 RetailRocket 样本上训练并比较 OxygenREC 消融变体。"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import asdict
import json
import math
from pathlib import Path
import random
import sys
import time

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import torch

from oxygenrec.data import (
    Split,
    TemporalBoundaries,
    build_frequency_bootstrap_registry,
    build_long_short_sid_model_batch,
    build_next_item_samples,
    build_sid_model_batch,
    load_retailrocket_events,
)
from oxygenrec.evaluation import evaluate_sid_ranking
from oxygenrec.instructions import build_history_instruction, encode_instructions
from oxygenrec.instruction_cache import (
    instruction_sample_key,
    load_instruction_feature_cache,
)
from oxygenrec.model import OxygenRECConfig, OxygenRECModel
from oxygenrec.sid import PrefixTrie
from oxygenrec.sid import SIDRegistry


IGR_VARIANTS = frozenset({
    "igr", "igr_q2i", "igr_generic_q2i", "igr_text_q2i", "igr_qwen_q2i",
})
Q2I_VARIANTS = frozenset({
    "q2i", "qwen_q2i", "igr_q2i", "igr_generic_q2i", "igr_text_q2i",
    "igr_qwen_q2i",
})
QWEN_VARIANTS = frozenset({"qwen_instruction", "qwen_q2i", "igr_qwen_q2i"})
V2_BEHAVIOR_VARIANTS = frozenset({"v2_behavior"})
V2_BEHAVIOR_WEIGHTS = (1.2, 1.5, 2.0)  # view/click代理、cart、order


def parse_args() -> argparse.Namespace:
    """定义数据、模型、消融变体、训练和评测参数。"""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--events", type=Path, default=Path("data/raw/retailrocket/events.csv"))
    parser.add_argument("--output-dir", type=Path, default=Path("checkpoints/retailrocket_phase1"))
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--seed", type=int, default=17)
    parser.add_argument(
        "--sample-seed", type=int, default=17,
        help="Fix the sampled cohort independently from model initialization seed.",
    )
    parser.add_argument("--max-items", type=int, default=50_000)
    parser.add_argument("--sid-width", type=int, default=64)
    parser.add_argument(
        "--sid-registry",
        type=Path,
        default=None,
        help="Use a fitted RQ registry instead of the temporary frequency bootstrap.",
    )
    parser.add_argument("--max-history", type=int, default=20)
    parser.add_argument("--long-history", type=int, default=100)
    parser.add_argument("--igr-top-k", type=int, default=10)
    parser.add_argument(
        "--variant", choices=("base", "behavior", "behavior_strength_decay", "instruction", "q2i", "qwen_instruction", "qwen_q2i", "igr", "igr_q2i", "igr_generic_q2i", "igr_text_q2i", "igr_qwen_q2i", "v2_behavior"),
        default="base",
    )
    parser.add_argument(
        "--instruction-feature-cache", type=Path, default=None,
        help=(
            "Qwen hidden-state cache generated by "
            "cache_qwen_instructions_retailrocket.py; required by qwen variants."
        ),
    )
    parser.add_argument("--q2i-weight", type=float, default=0.2)
    parser.add_argument(
        "--matched-igr-cohort", action="store_true",
        help="Use the IGR-eligible sample universe for every ablation variant.",
    )
    parser.add_argument("--max-train-samples", type=int, default=100_000)
    parser.add_argument("--max-validation-samples", type=int, default=100)
    parser.add_argument("--max-test-samples", type=int, default=1)
    parser.add_argument(
        "--evaluate-test", action="store_true",
        help="Evaluate the held-out test cohort once, using the best validation epoch.",
    )
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--learning-rate", type=float, default=3e-4)
    parser.add_argument("--hidden-size", type=int, default=128)
    parser.add_argument("--attention-heads", type=int, default=4)
    parser.add_argument("--encoder-layers", type=int, default=2)
    parser.add_argument("--decoder-layers", type=int, default=2)
    parser.add_argument("--beam-width", type=int, default=10)
    parser.add_argument(
        "--eval-only-checkpoint", type=Path, default=None,
        help="Load a checkpoint and run validation/retrieval diagnostics without training.",
    )
    parser.add_argument(
        "--init-checkpoint", type=Path, default=None,
        help=(
            "Warm-start all compatible model tensors from a common Base checkpoint; "
            "optimizer state is intentionally not restored."
        ),
    )
    parser.add_argument(
        "--retriever-init-checkpoint", type=Path, default=None,
        help="Initialize SID/instruction/Q2I modules from a Q2I-only checkpoint.",
    )
    parser.add_argument(
        "--history-context-instruction", action="store_true",
        help="Add a masked short-history pooling proxy to reasoning instruction.",
    )
    parser.add_argument(
        "--history-context-pooling", choices=("mean", "attention"), default="mean",
    )
    return parser.parse_args()


def tensor_batch(samples, registry, args, device, instruction_cache=None):
    """把 NextItemSample 转成模型 forward 可直接接收的 CUDA/CPU Tensor。"""
    uses_igr = args.variant in IGR_VARIANTS
    if uses_igr:
        batch = build_long_short_sid_model_batch(
            samples, registry, short_history_items=args.max_history,
            long_history_items=args.long_history,
            minimum_long_history_items=args.igr_top_k,
        )
        result = {
            "history_sids": torch.tensor(batch.short_history_sids, dtype=torch.long, device=device),
            "history_padding_mask": torch.tensor(batch.short_history_padding_mask, dtype=torch.bool, device=device),
            "target_sids": torch.tensor(batch.target_sids, dtype=torch.long, device=device),
            "scenario_ids": torch.tensor(batch.scenario_ids, dtype=torch.long, device=device),
            "long_history_sids": torch.tensor(batch.long_history_sids, dtype=torch.long, device=device),
            "long_history_padding_mask": torch.tensor(batch.long_history_padding_mask, dtype=torch.bool, device=device),
        }
        # RetailRocket 没有原论文的文本 instruction。这里用严格早于 target 的
        # 最近商品作为 trigger 代理，使 query 随用户上下文变化，而非每种行为一个常量。
        result["trigger_sids"] = result["history_sids"][:, -1, :]
        if args.variant == "igr_generic_q2i":
            result["scenario_ids"] = torch.zeros_like(result["scenario_ids"])
        if args.variant == "igr_text_q2i":
            texts = [
                build_history_instruction(
                    [event.behavior.value for event in sample.history]
                )[0]
                for sample in samples
            ]
            result["instruction_features"] = torch.tensor(
                encode_instructions(texts, 64), dtype=torch.float32, device=device,
            )
            # 推理时不知道 target 行为，因此文本变体只能用通用 scenario 和历史文本。
            result["scenario_ids"] = torch.zeros_like(result["scenario_ids"])
        if args.variant in QWEN_VARIANTS:
            if instruction_cache is None:
                raise ValueError(f"{args.variant} requires an instruction feature cache")
            features, sample_index = instruction_cache
            keys = [instruction_sample_key(sample) for sample in samples]
            missing = [key for key in keys if key not in sample_index]
            if missing:
                preview = ", ".join(missing[:3])
                raise KeyError(
                    f"instruction feature cache is missing {len(missing)} samples: {preview}"
                )
            rows = [sample_index[key] for key in keys]
            # 缓存保存在CPU/FP16；仅当前mini-batch转成模型adapter使用的FP32 CUDA特征。
            result["instruction_features"] = features[rows].to(
                device=device, dtype=torch.float32,
            )
            # 真实推理时目标行为未知，论文式Qwen特征使用通用scenario。
            result["scenario_ids"] = torch.zeros_like(result["scenario_ids"])
        return result
    batch = build_sid_model_batch(samples, registry, max_history_items=args.max_history)
    result = {
        "history_sids": torch.tensor(batch.history_sids, dtype=torch.long, device=device),
        "history_padding_mask": torch.tensor(batch.history_padding_mask, dtype=torch.bool, device=device),
        "target_sids": torch.tensor(batch.target_sids, dtype=torch.long, device=device),
    }
    if args.variant in V2_BEHAVIOR_VARIANTS:
        target_behavior_ids = torch.tensor(
            batch.target_behavior_ids, dtype=torch.long, device=device
        )
        behavior_weights = torch.tensor(
            V2_BEHAVIOR_WEIGHTS, dtype=torch.float32, device=device
        )
        result["history_behavior_ids"] = torch.tensor(
            batch.history_behavior_ids, dtype=torch.long, device=device,
        )
        result["behavior_instruction_ids"] = target_behavior_ids
        # 一个目标商品的三层SID token继承同一个行为价值权重。
        result["token_weights"] = behavior_weights[target_behavior_ids].unsqueeze(1).expand(
            -1, registry.levels
        )
    if args.variant in {"behavior", "behavior_strength_decay"}:
        result["history_behavior_ids"] = torch.tensor(
            batch.history_behavior_ids, dtype=torch.long, device=device,
        )
    if args.variant == "behavior_strength_decay":
        strength = {"view": 1.0, "addtocart": 2.0, "transaction": 3.0}
        result["sample_weights"] = torch.tensor(
            [strength[sample.target.behavior.value] for sample in samples],
            dtype=torch.float32, device=device,
        )
    if args.variant in {"instruction", "q2i"}:
        scenario = {"view": 0, "addtocart": 1, "transaction": 2}
        result["scenario_ids"] = torch.tensor(
            [scenario[sample.target.behavior.value] for sample in samples],
            dtype=torch.long, device=device,
        )
        result["trigger_sids"] = result["history_sids"][:, -1, :]
    if args.variant in QWEN_VARIANTS:
        if instruction_cache is None:
            raise ValueError(f"{args.variant} requires an instruction feature cache")
        features, sample_index = instruction_cache
        keys = [instruction_sample_key(sample) for sample in samples]
        missing = [key for key in keys if key not in sample_index]
        if missing:
            preview = ", ".join(missing[:3])
            raise KeyError(
                f"instruction feature cache is missing {len(missing)} samples: {preview}"
            )
        rows = [sample_index[key] for key in keys]
        result["instruction_features"] = features[rows].to(
            device=device, dtype=torch.float32,
        )
        # target行为在推理时未知；新主线只传历史末项和Slow特征。
        result["scenario_ids"] = torch.zeros(
            len(samples), dtype=torch.long, device=device,
        )
        result["trigger_sids"] = result["history_sids"][:, -1, :]
    return result


def chunks(items, size):
    """把样本列表切成不超过 size 的连续 mini-batch。"""
    for start in range(0, len(items), size):
        yield items[start : start + size]


def load_compatible_model_checkpoint(
    model, checkpoint_path, *, device, registry_version, boundaries,
):
    """加载共同Base权重；只允许历史位置表做可解释的前缀扩展。"""
    payload = torch.load(checkpoint_path, map_location=device, weights_only=False)
    if payload.get("sid_registry_version") != registry_version:
        raise ValueError("init checkpoint SID registry version mismatch")
    if payload.get("boundaries") != asdict(boundaries):
        raise ValueError("init checkpoint temporal boundaries mismatch")
    source_config = payload.get("model_config")
    if not isinstance(source_config, dict):
        raise ValueError("init checkpoint does not contain model_config")
    target_config = asdict(model.config)
    structural_fields = (
        "sid_width", "sid_levels", "instruction_vocab_size",
        "scenario_vocab_size", "behavior_vocab_size",
        "behavior_instruction_vocab_size", "behavior_time_decay",
        "use_history_context_instruction", "history_context_pooling",
        "q2i_dimension", "q2i_variance_weight", "q2i_decorrelation_weight",
        "hidden_size", "attention_heads", "encoder_layers", "decoder_layers",
        "feedforward_size", "dropout", "max_history_items",
        "max_target_items", "max_future_items",
    )
    config_mismatches = {
        name: {"expected": target_config[name], "actual": source_config.get(name)}
        for name in structural_fields
        if source_config.get(name) != target_config[name]
    }
    if config_mismatches:
        raise ValueError(
            "init checkpoint structural model config mismatch: "
            + json.dumps(config_mismatches, sort_keys=True)
        )
    required_base_values = {
        "instruction_feature_size": 0,
        "q2i_weight": 0.0,
        "igr_top_k": 0,
    }
    non_base = {
        name: {"expected": expected, "actual": source_config.get(name)}
        for name, expected in required_base_values.items()
        if source_config.get(name) != expected
    }
    if non_base:
        raise ValueError(
            "init checkpoint is not a plain Base checkpoint: "
            + json.dumps(non_base, sort_keys=True)
        )
    source = payload.get("model_state")
    if not isinstance(source, dict):
        raise ValueError("init checkpoint does not contain model_state")
    current = model.state_dict()
    exact = []
    partial = []
    skipped = []
    for name, tensor in source.items():
        if name not in current:
            skipped.append(name)
            continue
        if current[name].shape == tensor.shape:
            current[name] = tensor
            exact.append(name)
            continue
        if (
            name == "history_positions.weight"
            and current[name].ndim == tensor.ndim == 2
            and current[name].shape[1:] == tensor.shape[1:]
        ):
            rows = min(current[name].shape[0], tensor.shape[0])
            current[name][:rows].copy_(tensor[:rows])
            partial.append({"name": name, "copied_rows": rows})
            continue
        skipped.append(name)
    if not exact:
        raise RuntimeError("init checkpoint has no shape-compatible model tensors")
    model.load_state_dict(current)
    return {
        "checkpoint": str(checkpoint_path),
        "source_epoch": payload.get("epoch"),
        "exact_tensors": len(exact),
        "partial_tensors": partial,
        "skipped_tensors": len(skipped),
    }


@torch.no_grad()
def validate(model, samples, registry, trie, args, device, instruction_cache=None):
    """执行 beam 排序指标以及 IGR/Q2I 诊断，不构建梯度。"""
    model.eval()
    predictions = []
    targets = []
    repeat_eligible = 0
    repeat_retrieved = 0
    repeat_recent_retrieved = 0
    repeat_random_expected_hits = 0.0
    exact_repeat_eligible = 0
    exact_repeat_retrieved = 0
    exact_repeat_recent_retrieved = 0
    exact_repeat_random_expected_hits = 0.0
    q2i_alignment_weighted_sum = 0.0
    q2i_alignment_sample_count = 0
    q2i_cosines = []
    for sample_batch in chunks(samples, args.batch_size):
        batch = tensor_batch(
            sample_batch, registry, args, device,
            instruction_cache=instruction_cache,
        )
        target_sids = batch.pop("target_sids")
        batch.pop("sample_weights", None)
        batch.pop("token_weights", None)
        diagnostic = None
        if args.variant in IGR_VARIANTS:
            # teacher-forcing forward 用于读取 IGR 索引和 Q2I alignment 诊断。
            diagnostic = model(
                target_sids=target_sids,
                compute_q2i_diagnostics=True,
                **batch,
            )
            long_sids = batch["long_history_sids"]
            long_mask = batch["long_history_padding_mask"]
            selected = long_sids.gather(
                1,
                diagnostic.igr_indices.unsqueeze(-1).expand(
                    -1, -1, long_sids.shape[-1]
                ),
            )
            target_matches = (long_sids == target_sids.unsqueeze(1)).all(dim=-1) & ~long_mask
            selected_matches = (selected == target_sids.unsqueeze(1)).all(dim=-1)
            repeat_eligible += int(target_matches.any(dim=1).sum())
            repeat_retrieved += int(
                (target_matches.any(dim=1) & selected_matches.any(dim=1)).sum()
            )
            recent_matches = target_matches[:, -args.igr_top_k :].any(dim=1)
            eligible_rows = target_matches.any(dim=1)
            repeat_recent_retrieved += int((eligible_rows & recent_matches).sum())
            for row in range(target_matches.shape[0]):
                if not bool(eligible_rows[row]):
                    continue
                valid_count = int((~long_mask[row]).sum())
                match_count = int(target_matches[row].sum())
                misses = valid_count - match_count
                miss_probability = (
                    math.comb(misses, args.igr_top_k)
                    / math.comb(valid_count, args.igr_top_k)
                    if misses >= args.igr_top_k else 0.0
                )
                repeat_random_expected_hits += 1.0 - miss_probability
            # SID碰撞会把不同item误算成重复命中，因此同时报告exact-item口径。
            for row, sample in enumerate(sample_batch):
                known_events = [
                    event for event in sample.history
                    if event.item_id in registry.item_to_sid
                ]
                short_events = known_events[-args.max_history:]
                long_events = (
                    known_events[: -len(short_events)][-args.long_history:]
                    if short_events else []
                )
                padding = args.long_history - len(long_events)
                exact_matches = [
                    event.item_id == sample.target.item_id for event in long_events
                ]
                if not any(exact_matches):
                    continue
                exact_repeat_eligible += 1
                selected_positions = [
                    int(index) - padding
                    for index in diagnostic.igr_indices[row].detach().cpu().tolist()
                ]
                exact_repeat_retrieved += int(any(
                    0 <= position < len(exact_matches) and exact_matches[position]
                    for position in selected_positions
                ))
                exact_repeat_recent_retrieved += int(
                    any(exact_matches[-args.igr_top_k:])
                )
                match_count = sum(exact_matches)
                misses = len(exact_matches) - match_count
                miss_probability = (
                    math.comb(misses, args.igr_top_k)
                    / math.comb(len(exact_matches), args.igr_top_k)
                    if misses >= args.igr_top_k else 0.0
                )
                exact_repeat_random_expected_hits += 1.0 - miss_probability
        elif args.variant in QWEN_VARIANTS:
            # B/C在相同target上计算只读cosine，使Q2I前后机制指标可比较。
            diagnostic = model(
                target_sids=target_sids,
                compute_q2i_diagnostics=True,
                **batch,
            )
        if diagnostic is not None and diagnostic.q2i_alignment_loss is not None:
            q2i_alignment_weighted_sum += (
                float(diagnostic.q2i_alignment_loss) * len(sample_batch)
            )
            q2i_alignment_sample_count += len(sample_batch)
        if diagnostic is not None and diagnostic.q2i_cosine is not None:
            q2i_cosines.extend(
                float(value) for value in diagnostic.q2i_cosine.detach().cpu()
            )
        # 真正的推荐排序来自 PrefixTrie 约束 beam search，而非上面的诊断 forward。
        output = model.beam_search(
            batch.pop("history_sids"), batch.pop("history_padding_mask"), trie,
            beam_width=args.beam_width, **batch,
        )
        predictions.extend(output.semantic_ids.cpu().tolist())
        targets.extend(sample.target.item_id for sample in sample_batch)
    available = min(len(ranking) for ranking in predictions)
    ks = tuple(k for k in (1, 5, 10) if k <= available)
    metrics = evaluate_sid_ranking(predictions, targets, registry, ks=ks)
    behavior_metrics = {}
    for behavior in ("view", "addtocart", "transaction"):
        indices = [
            index for index, sample in enumerate(samples)
            if sample.target.behavior.value == behavior
        ]
        if not indices:
            continue
        subset = evaluate_sid_ranking(
            [predictions[index] for index in indices],
            [targets[index] for index in indices], registry, ks=ks,
        )
        behavior_metrics[behavior] = {
            "count": subset.sample_count,
            "hr": dict(subset.hit_rate),
            "mrr": subset.mrr,
            "ndcg": subset.ndcg,
        }
    retrieval = {
        "repeat_eligible": repeat_eligible,
        "repeat_retrieved": repeat_retrieved,
        "repeat_recall": (
            repeat_retrieved / repeat_eligible if repeat_eligible else None
        ),
        "repeat_recent_recall": (
            repeat_recent_retrieved / repeat_eligible if repeat_eligible else None
        ),
        "repeat_random_expected_recall": (
            repeat_random_expected_hits / repeat_eligible if repeat_eligible else None
        ),
        "repeat_lift_over_random": (
            (repeat_retrieved / repeat_random_expected_hits)
            if repeat_random_expected_hits else None
        ),
        "exact_repeat_eligible": exact_repeat_eligible,
        "exact_repeat_retrieved": exact_repeat_retrieved,
        "exact_repeat_recall": (
            exact_repeat_retrieved / exact_repeat_eligible
            if exact_repeat_eligible else None
        ),
        "exact_repeat_recent_recall": (
            exact_repeat_recent_retrieved / exact_repeat_eligible
            if exact_repeat_eligible else None
        ),
        "exact_repeat_random_expected_recall": (
            exact_repeat_random_expected_hits / exact_repeat_eligible
            if exact_repeat_eligible else None
        ),
        "exact_repeat_lift_over_random": (
            exact_repeat_retrieved / exact_repeat_random_expected_hits
            if exact_repeat_random_expected_hits else None
        ),
        "q2i_alignment": (
            q2i_alignment_weighted_sum / q2i_alignment_sample_count
            if q2i_alignment_sample_count else None
        ),
        "q2i_alignment_loss": (
            q2i_alignment_weighted_sum / q2i_alignment_sample_count
            if q2i_alignment_sample_count else None
        ),
        "q2i_cosine": (
            sum(q2i_cosines) / len(q2i_cosines) if q2i_cosines else None
        ),
        "q2i_cosine_count": len(q2i_cosines),
        "behavior_metrics": behavior_metrics,
    }
    return metrics, retrieval


def main() -> int:
    """串起事件读取、时间切分、SID 映射、训练、验证和 checkpoint 保存。"""
    args = parse_args()
    if args.igr_top_k > args.long_history:
        raise ValueError("igr-top-k cannot exceed long-history")
    if args.init_checkpoint is not None and args.retriever_init_checkpoint is not None:
        raise ValueError("init-checkpoint and retriever-init-checkpoint are mutually exclusive")
    if args.eval_only_checkpoint is not None and args.init_checkpoint is not None:
        raise ValueError("eval-only-checkpoint and init-checkpoint are mutually exclusive")
    if not args.events.is_file():
        raise FileNotFoundError(args.events)
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    device = torch.device(args.device)

    print("stage=load_events")
    events = list(load_retailrocket_events(args.events))
    minimum = min(event.timestamp_ms for event in events)
    maximum = max(event.timestamp_ms for event in events)
    duration = maximum - minimum + 1
    # 全局 80%/10%/10% 时间切分；所有用户共享同一边界。
    boundaries = TemporalBoundaries(
        train_end_ms=minimum + duration * 8 // 10,
        validation_end_ms=minimum + duration * 9 // 10,
    )
    if args.sid_registry is None:
        registry = build_frequency_bootstrap_registry(
            events,
            boundaries,
            max_items=args.max_items,
            width=args.sid_width,
        )
    else:
        registry = SIDRegistry.from_json(args.sid_registry)
    in_vocabulary = registry.item_to_sid
    filtered_events = [event for event in events if event.item_id in in_vocabulary]
    del events
    print("stage=build_samples")
    uses_igr = args.variant in IGR_VARIANTS
    matched_cohort = uses_igr or args.matched_igr_cohort
    samples = build_next_item_samples(
        filtered_events,
        boundaries,
        min_history=args.max_history + args.igr_top_k if matched_cohort else 1,
        max_history=(args.max_history + args.long_history) if matched_cohort else args.max_history,
        max_samples_per_split={
            Split.TRAIN: args.max_train_samples,
            Split.VALIDATION: args.max_validation_samples,
            Split.TEST: args.max_test_samples,
        },
        sample_seed=args.sample_seed,
    )
    by_split = defaultdict(list)
    for sample in samples:
        by_split[sample.split].append(sample)
    train_samples = by_split[Split.TRAIN]
    validation_samples = by_split[Split.VALIDATION]
    test_samples = by_split[Split.TEST]
    if not train_samples or not validation_samples:
        raise RuntimeError("bounded experiment produced an empty train or validation split")
    if args.evaluate_test and not test_samples:
        raise RuntimeError("--evaluate-test requires a non-empty test split")
    print(
        f"stage=samples variant={args.variant} matched_cohort={matched_cohort} "
        f"train={len(train_samples)} validation={len(validation_samples)} "
        f"test={len(test_samples)} model_seed={args.seed} sample_seed={args.sample_seed} "
        f"train_behaviors={dict(sorted(Counter(sample.target.behavior.value for sample in train_samples).items()))} "
        f"behavior_weights={V2_BEHAVIOR_WEIGHTS if args.variant in V2_BEHAVIOR_VARIANTS else None}"
    )

    instruction_cache = None
    instruction_cache_metadata = None
    instruction_feature_size = 64 if args.variant == "igr_text_q2i" else 0
    if args.variant in QWEN_VARIANTS:
        if args.instruction_feature_cache is None:
            raise ValueError(
                f"--instruction-feature-cache is required for {args.variant}"
            )
        features, sample_index, metadata = load_instruction_feature_cache(
            args.instruction_feature_cache
        )
        expected_metadata = {
            "sid_registry_version": registry.version,
            "boundaries": asdict(boundaries),
            "sample_seed": args.sample_seed,
            "short_history": args.max_history,
            "long_history": args.long_history,
            "igr_top_k": args.igr_top_k,
        }
        mismatches = {
            name: {"expected": expected, "actual": metadata.get(name)}
            for name, expected in expected_metadata.items()
            if metadata.get(name) != expected
        }
        if mismatches:
            raise ValueError(
                "instruction feature cache metadata mismatch: "
                + json.dumps(mismatches, ensure_ascii=False, sort_keys=True)
            )
        required_keys = {
            instruction_sample_key(sample)
            for sample in train_samples + validation_samples
            + (test_samples if args.evaluate_test else [])
        }
        missing_keys = required_keys.difference(sample_index)
        if missing_keys:
            raise ValueError(
                "instruction feature cache does not cover the current cohort: "
                f"missing={len(missing_keys)}"
            )
        instruction_cache = (features, sample_index)
        instruction_cache_metadata = metadata
        instruction_feature_size = int(features.shape[1])
        print(
            f"stage=instruction_cache path={args.instruction_feature_cache} "
            f"rows={features.shape[0]} feature_size={instruction_feature_size} "
            f"covered={len(required_keys)}"
        )

    # variant 只打开对应模块，便于 base/instruction/Q2I/IGR 做同口径消融。
    config = OxygenRECConfig(
        sid_width=registry.width,
        sid_levels=registry.levels,
        hidden_size=args.hidden_size,
        attention_heads=args.attention_heads,
        encoder_layers=args.encoder_layers,
        decoder_layers=args.decoder_layers,
        feedforward_size=args.hidden_size * 4,
        max_history_items=args.max_history,
        scenario_vocab_size=3 if args.variant in {"instruction", "q2i", "igr", "igr_q2i"} else 1,
        instruction_feature_size=instruction_feature_size,
        behavior_vocab_size=(
            3
            if args.variant in {"behavior", "behavior_strength_decay"}
            or args.variant in V2_BEHAVIOR_VARIANTS
            else 0
        ),
        behavior_instruction_vocab_size=3 if args.variant in V2_BEHAVIOR_VARIANTS else 0,
        behavior_time_decay=0.05 if args.variant == "behavior_strength_decay" else 0.0,
        igr_top_k=args.igr_top_k if uses_igr else 0,
        q2i_weight=args.q2i_weight if args.variant in Q2I_VARIANTS else 0.0,
        use_history_context_instruction=args.history_context_instruction,
        history_context_pooling=args.history_context_pooling,
    )
    model = OxygenRECModel(config)
    if args.variant in QWEN_VARIANTS:
        # IGR会扩大history position表并改变后续默认RNG消费；显式重置新加的
        # Qwen adapter，保证B/C/D在同一model seed下从完全相同的adapter开始。
        with torch.random.fork_rng(devices=[]):
            torch.manual_seed(args.seed + 100_003)
            model.instruction_feature_adapter.reset_parameters()
    model = model.to(device)
    warm_start = None
    if args.init_checkpoint is not None:
        warm_start = load_compatible_model_checkpoint(
            model, args.init_checkpoint, device=device,
            registry_version=registry.version, boundaries=boundaries,
        )
        print("stage=warm_start " + json.dumps(warm_start, sort_keys=True))
    if args.retriever_init_checkpoint is not None:
        if args.variant not in IGR_VARIANTS:
            raise ValueError("retriever initialization is only valid for IGR variants")
        source = torch.load(
            args.retriever_init_checkpoint, map_location=device, weights_only=False
        )["model_state"]
        prefixes = (
            "sid_embeddings.", "instruction_embeddings.", "scenario_embeddings.",
            "instruction_feature_adapter.", "query_adapter.", "item_adapter.",
            "history_context_adapter.",
            "history_context_query.", "history_context_key.", "history_context_value.",
        )
        current = model.state_dict()
        transferred = {
            name: tensor
            for name, tensor in source.items()
            if name.startswith(prefixes)
            and name in current
            and current[name].shape == tensor.shape
        }
        if not transferred:
            raise RuntimeError("retriever init checkpoint has no compatible parameters")
        incompatible = model.load_state_dict(transferred, strict=False)
        print(
            f"stage=retriever_init transferred_tensors={len(transferred)} "
            f"missing_tensors={len(incompatible.missing_keys)}"
        )
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)
    parameter_count = sum(parameter.numel() for parameter in model.parameters())
    trainable_parameter_count = sum(
        parameter.numel() for parameter in model.parameters()
        if parameter.requires_grad
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    registry.to_json(args.output_dir / "sid_registry.json")
    trie = PrefixTrie.from_registry(registry)
    epoch_records = []
    best_record = None
    best_score = None

    if args.eval_only_checkpoint is not None:
        checkpoint = torch.load(
            args.eval_only_checkpoint, map_location=device, weights_only=False
        )
        model.load_state_dict(checkpoint["model_state"])
        metrics, retrieval = validate(
            model, validation_samples, registry, trie, args, device,
            instruction_cache=instruction_cache,
        )
        print(
            f"EVAL variant={args.variant} checkpoint_epoch={checkpoint['epoch']} "
            f"hr={dict(metrics.hit_rate)} mrr={metrics.mrr:.6f} "
            f"repeat_recall={retrieval['repeat_recall']} "
            f"repeat_recent={retrieval['repeat_recent_recall']} "
            f"repeat_random={retrieval['repeat_random_expected_recall']} "
            f"repeat_lift={retrieval['repeat_lift_over_random']} "
            f"repeat_eligible={retrieval['repeat_eligible']} "
            f"exact_repeat_recall={retrieval['exact_repeat_recall']} "
            f"q2i_cosine={retrieval['q2i_cosine']} "
            f"behavior_metrics={json.dumps(retrieval['behavior_metrics'], sort_keys=True)}"
        )
        return 0

    for epoch in range(1, args.epochs + 1):
        epoch_started = time.perf_counter()
        model.train()
        random.shuffle(train_samples)
        total_loss = 0.0
        total_ntp_loss = 0.0
        total_q2i_loss = 0.0
        max_loss_identity_error = 0.0
        max_behavior_adapter_grad = 0.0
        max_reserved_token_grad = 0.0
        batches = 0
        for sample_batch in chunks(train_samples, args.batch_size):
            batch = tensor_batch(
                sample_batch, registry, args, device,
                instruction_cache=instruction_cache,
            )
            optimizer.zero_grad(set_to_none=True)
            # 主训练前向：返回 weighted NTP，以及可选 Q2I 联合损失。
            output = model(**batch)
            expected_loss = output.ntp_loss
            if output.q2i_loss is not None:
                expected_loss = expected_loss + config.q2i_weight * output.q2i_loss
            identity_error = float((output.loss - expected_loss).abs().detach())
            if identity_error > 1e-5:
                raise RuntimeError(
                    "joint-loss identity failed: "
                    f"loss={float(output.loss.detach()):.6f} "
                    f"ntp={float(output.ntp_loss.detach()):.6f} "
                    f"q2i={float(output.q2i_loss.detach()) if output.q2i_loss is not None else None} "
                    f"weight={config.q2i_weight}"
                )
            output.loss.backward()
            if args.variant in V2_BEHAVIOR_VARIANTS:
                max_behavior_adapter_grad = max(
                    max_behavior_adapter_grad,
                    sum(
                        float(parameter.grad.abs().sum())
                        for parameter in model.behavior_instruction_adapter.parameters()
                        if parameter.grad is not None
                    ),
                )
                embedding_grad = model.sid_embeddings[0].weight.grad
                if embedding_grad is not None:
                    max_reserved_token_grad = max(
                        max_reserved_token_grad,
                        float(embedding_grad[registry.width :].abs().sum()),
                    )
            optimizer.step()
            total_loss += float(output.loss.detach())
            total_ntp_loss += float(output.ntp_loss.detach())
            if output.q2i_loss is not None:
                total_q2i_loss += float(output.q2i_loss.detach())
            max_loss_identity_error = max(max_loss_identity_error, identity_error)
            batches += 1
        train_seconds = time.perf_counter() - epoch_started
        validation_started = time.perf_counter()
        metrics, retrieval = validate(
            model, validation_samples, registry, trie, args, device,
            instruction_cache=instruction_cache,
        )
        validation_seconds = time.perf_counter() - validation_started
        checkpoint = {
            "epoch": epoch,
            "model_config": asdict(config),
            "model_state": model.state_dict(),
            "optimizer_state": optimizer.state_dict(),
            "sid_registry_version": registry.version,
            "boundaries": asdict(boundaries),
            "args": vars(args),
        }
        torch.save(checkpoint, args.output_dir / f"epoch-{epoch}.pt")
        q2i_summary = (
            f" q2i_loss={total_q2i_loss / batches:.6f}"
            if args.variant in Q2I_VARIANTS else ""
        )
        mean_loss = total_loss / batches
        mean_ntp_loss = total_ntp_loss / batches
        epoch_identity_error = 0.0
        if args.variant in Q2I_VARIANTS:
            mean_q2i_loss = total_q2i_loss / batches
            reconstructed = mean_ntp_loss + config.q2i_weight * mean_q2i_loss
            epoch_identity_error = abs(mean_loss - reconstructed)
            if epoch_identity_error > 1e-5:
                raise RuntimeError(
                    "epoch joint-loss identity failed: "
                    f"loss={mean_loss:.6f} ntp={mean_ntp_loss:.6f} "
                    f"q2i={mean_q2i_loss:.6f} weight={config.q2i_weight}"
                )
        print(
            f"variant={args.variant} epoch={epoch} train_loss={mean_loss:.6f} "
            f"ntp_loss={mean_ntp_loss:.6f}{q2i_summary} "
            f"q2i_weight={config.q2i_weight:.6f} "
            f"loss_identity_error={max_loss_identity_error:.3e} "
            f"epoch_identity_error={epoch_identity_error:.3e} "
            f"hr={dict(metrics.hit_rate)} mrr={metrics.mrr:.6f} "
            f"legal_sid_rate={metrics.legal_sid_rate:.6f} "
            f"repeat_recall={retrieval['repeat_recall']} "
            f"repeat_recent={retrieval['repeat_recent_recall']} "
            f"repeat_random={retrieval['repeat_random_expected_recall']} "
            f"repeat_lift={retrieval['repeat_lift_over_random']} "
            f"q2i_alignment={retrieval['q2i_alignment']} "
            f"q2i_cosine={retrieval['q2i_cosine']} "
            f"repeat_eligible={retrieval['repeat_eligible']} "
            f"exact_repeat_recall={retrieval['exact_repeat_recall']} "
            f"exact_repeat_recent={retrieval['exact_repeat_recent_recall']} "
            f"exact_repeat_random={retrieval['exact_repeat_random_expected_recall']} "
            f"exact_repeat_eligible={retrieval['exact_repeat_eligible']} "
            f"train_samples_per_second={len(train_samples) / train_seconds:.3f} "
            f"behavior_metrics={json.dumps(retrieval['behavior_metrics'], sort_keys=True)} "
            f"ib_adapter_grad={max_behavior_adapter_grad:.6f} "
            f"reserved_token_grad={max_reserved_token_grad:.6f}"
        )
        epoch_records.append({
            "variant": args.variant,
            "seed": args.seed,
            "sample_seed": args.sample_seed,
            "epoch": epoch,
            "train_samples": len(train_samples),
            "validation_samples": len(validation_samples),
            "test_samples": len(test_samples),
            "train_loss": mean_loss,
            "ntp_loss": mean_ntp_loss,
            "q2i_loss": (
                total_q2i_loss / batches
                if args.variant in Q2I_VARIANTS else None
            ),
            "q2i_weight": config.q2i_weight,
            "loss_identity_error": max_loss_identity_error,
            "epoch_identity_error": epoch_identity_error,
            "hit_rate": dict(metrics.hit_rate),
            "mrr": metrics.mrr,
            "ndcg": metrics.ndcg,
            "legal_sid_rate": metrics.legal_sid_rate,
            "retrieval": retrieval,
            "train_seconds": train_seconds,
            "validation_seconds": validation_seconds,
            "train_samples_per_second": len(train_samples) / train_seconds,
            "parameter_count": parameter_count,
            "trainable_parameter_count": trainable_parameter_count,
            "warm_start": warm_start,
            "sid_registry_version": registry.version,
            "boundaries": asdict(boundaries),
            "instruction_cache": (
                str(args.instruction_feature_cache)
                if args.instruction_feature_cache is not None else None
            ),
            "instruction_cache_metadata": instruction_cache_metadata,
            "model_config": asdict(config),
            "experiment_protocol": {
                "max_history": args.max_history,
                "long_history": args.long_history,
                "igr_top_k": args.igr_top_k,
                "matched_igr_cohort": args.matched_igr_cohort,
                "batch_size": args.batch_size,
                "epochs": args.epochs,
                "learning_rate": args.learning_rate,
                "beam_width": args.beam_width,
                "q2i_weight_argument": args.q2i_weight,
            },
        })
        current_record = epoch_records[-1]
        hr5 = current_record["hit_rate"].get(5, current_record["hit_rate"].get("5", 0.0))
        score = (hr5, current_record["mrr"], current_record["ndcg"], -mean_loss)
        if best_score is None or score > best_score:
            best_score = score
            best_record = current_record
            torch.save(checkpoint, args.output_dir / "best.pt")
        (args.output_dir / "metrics.jsonl").write_text(
            "".join(json.dumps(record, sort_keys=True) + "\n" for record in epoch_records),
            encoding="utf-8",
        )
    if best_record is None:  # pragma: no cover - epochs is positive in normal use
        raise RuntimeError("training did not produce an epoch record")
    result = dict(best_record)
    result["selection"] = {
        "split": "validation",
        "metric_order": ["hr@5", "mrr", "ndcg", "negative_train_loss"],
        "best_epoch": best_record["epoch"],
    }
    if args.evaluate_test:
        best_checkpoint = torch.load(
            args.output_dir / "best.pt", map_location=device, weights_only=False,
        )
        model.load_state_dict(best_checkpoint["model_state"])
        test_started = time.perf_counter()
        test_metrics, test_retrieval = validate(
            model, test_samples, registry, trie, args, device,
            instruction_cache=instruction_cache,
        )
        result["test"] = {
            "sample_count": test_metrics.sample_count,
            "hit_rate": dict(test_metrics.hit_rate),
            "mrr": test_metrics.mrr,
            "ndcg": test_metrics.ndcg,
            "legal_sid_rate": test_metrics.legal_sid_rate,
            "retrieval": test_retrieval,
            "evaluation_seconds": time.perf_counter() - test_started,
        }
    (args.output_dir / "result.json").write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8",
    )
    print(
        f"RESULT variant={args.variant} seed={args.seed} "
        f"best_epoch={best_record['epoch']} result={args.output_dir / 'result.json'} "
        f"best_checkpoint={args.output_dir / 'best.pt'}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
